# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bda3437d57f95eb11318bbb80275341b8638a127ac9f9412d4f25280c104d767eb3241e28a053724563186eec853bf9e1de879100230b611d54d5d90d998f315

test:
  secret_key_base: c2b7e95811cceb0003c7c4aebf732fdddda24fa7a3161a3841567c3b1d0d1bcd8526838d8b2ae249df7b9cd5e23b51b872fde5dffd009974270ea8db51924ee4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
